import { createStateMachine } from '../state-machine.js';

function createDefaultCapabilities() {
    return {
        protocolVersion: 0,
        minSupportedProtocolVersion: 0,
        nativeSaveSupport: false,
        nativeSaveCompatibilityDetail: '',
        compatibilityCheckedAt: null,
        userDirectorySupport: false,
        userDirectoryScanSupport: false,
        termux: false,
        termuxCheckedAt: null,
    };
}

export function createRuntime() {
    return {
        settings: null,
        diagnostics: null,
        releaseInfo: null,
        chatState: null,
        quickReplyStatus: null,
        capabilities: createDefaultCapabilities(),
        termuxAvailable: false,
        machine: createStateMachine(),
        activeJobId: null,
        activeJobStatus: null,
        activeJobStatusSource: 'none',
        activeJobStatusObservedAt: null,
        committedReloadKeys: new Set(),
        lastAppliedVersion: 0,
        manualStopRequested: false,
        nativeFailureCompatWarned: false,
        nativeFailureReported: false,
        mountRetryHandle: 0,
        hostObserver: null,
        quickReplyRefreshHandle: 0,
        recoveryHandle: 0,
        recoveryPromise: null,
        recoverySignalsBound: false,
        poll: {
            handle: 0,
            unchangedCount: 0,
            transientFailures: 0,
            unexpectedServerFailures: 0,
            signature: '',
        },
        transport: {
            lastError: null,
            lastEndpoint: '',
            lastErrorAt: null,
            errorContext: null,
            disconnectPolicy: 'none',
        },
        capture: {
            session: null,
            request: null,
            fingerprint: null,
            assistantMessageIndex: null,
        },
        log: {
            text: '',
            jobId: '',
            title: '',
            updatedAt: null,
            entryCount: 0,
            show: false,
        },
        ui: {
            panel: null,
            statusText: null,
            stats: null,
            errorBox: null,
            actionToggleButton: null,
            quickReplyStatusLine: null,
            quickReplyToggleButton: null,
            mainPane: null,
            systemPane: null,
            diagnosticsOutput: null,
            retryLogShell: null,
            retryLogContainer: null,
            releaseInfoContainer: null,
            activeTab: 'main',
        },
    };
}
