import { createStateMachine } from '../state-machine.js';

function createDefaultCapabilities() {
    return {
        protocolVersion: 0,
        minSupportedProtocolVersion: 0,
        nativeSaveSupport: false,
        nativeSaveCompatibilityDetail: '',
        compatibilityCheckedAt: null,
        userDirectorySupport: false,
        userDirectoryScanSupport: false,
        termux: false,
        termuxCheckedAt: null,
    };
}

export function createRuntime() {
    return {
        settings: null,
        diagnostics: null,
        panel: null,
        statusText: null,
        stats: null,
        diagnosticsOutput: null,
        retryLogShell: null,
        retryLogContainer: null,
        releaseInfoContainer: null,
        errorBox: null,
        actionToggleButton: null,
        quickReplyStatusLine: null,
        quickReplyToggleButton: null,
        mainPane: null,
        systemPane: null,
        machine: createStateMachine(),
        captureSession: null,
        activeJobId: null,
        activeJobStatus: null,
        activeJobStatusSource: 'none',
        activeJobStatusObservedAt: null,
        retryLogText: '',
        retryLogJobId: '',
        retryLogTitle: '',
        retryLogUpdatedAt: null,
        retryLogEntryCount: 0,
        chatState: null,
        quickReplyStatus: null,
        pollHandle: 0,
        pollUnchangedCount: 0,
        pollTransientFailures: 0,
        pollUnexpectedServerFailures: 0,
        pollSignature: '',
        committedReloadKeys: new Set(),
        lastAppliedVersion: 0,
        manualStopRequested: false,
        mountRetryHandle: 0,
        hostObserver: null,
        quickReplyRefreshHandle: 0,
        capturedRequest: null,
        fingerprint: null,
        assistantMessageIndex: null,
        capabilities: createDefaultCapabilities(),
        termuxAvailable: false,
        releaseInfo: null,
        showRetryLog: false,
        activeTab: 'main',
        nativeFailureCompatWarned: false,
        nativeFailureReported: false,
        lastTransportError: null,
        lastTransportEndpoint: '',
        lastTransportErrorAt: null,
        transportErrorContext: null,
        disconnectPolicy: 'none',
        recoveryHandle: 0,
        recoveryPromise: null,
        recoverySignalsBound: false,
    };
}
